package mybatis.domain;

public class LdHomeWorkFB {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.my_id
     *
     * @mbg.generated
     */
    private Long myId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.homework_id
     *
     * @mbg.generated
     */
    private Long homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.level_flag
     *
     * @mbg.generated
     */
    private String levelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomeworkfb.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.id
     *
     * @return the value of ldhomeworkfb.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.id
     *
     * @param id the value for ldhomeworkfb.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.my_id
     *
     * @return the value of ldhomeworkfb.my_id
     *
     * @mbg.generated
     */
    public Long getMyId() {
        return myId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.my_id
     *
     * @param myId the value for ldhomeworkfb.my_id
     *
     * @mbg.generated
     */
    public void setMyId(Long myId) {
        this.myId = myId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.user_id
     *
     * @return the value of ldhomeworkfb.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.user_id
     *
     * @param userId the value for ldhomeworkfb.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.homework_id
     *
     * @return the value of ldhomeworkfb.homework_id
     *
     * @mbg.generated
     */
    public Long getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.homework_id
     *
     * @param homeworkId the value for ldhomeworkfb.homework_id
     *
     * @mbg.generated
     */
    public void setHomeworkId(Long homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.level_flag
     *
     * @return the value of ldhomeworkfb.level_flag
     *
     * @mbg.generated
     */
    public String getLevelFlag() {
        return levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.level_flag
     *
     * @param levelFlag the value for ldhomeworkfb.level_flag
     *
     * @mbg.generated
     */
    public void setLevelFlag(String levelFlag) {
        this.levelFlag = levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomeworkfb.mark
     *
     * @return the value of ldhomeworkfb.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomeworkfb.mark
     *
     * @param mark the value for ldhomeworkfb.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}