package mybatis.domain;

import java.util.Date;

public class LdHomeWork {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.class_id
     *
     * @mbg.generated
     */
    private Long classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.lession_id
     *
     * @mbg.generated
     */
    private Long lessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.homework_filepath
     *
     * @mbg.generated
     */
    private String homeworkFilepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.homework_filename
     *
     * @mbg.generated
     */
    private String homeworkFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.correct_flag
     *
     * @mbg.generated
     */
    private String correctFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.star_count
     *
     * @mbg.generated
     */
    private Integer starCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.negative_count
     *
     * @mbg.generated
     */
    private Integer negativeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldhomework.best_flag
     *
     * @mbg.generated
     */
    private String bestFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.id
     *
     * @return the value of ldhomework.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.id
     *
     * @param id the value for ldhomework.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.user_id
     *
     * @return the value of ldhomework.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.user_id
     *
     * @param userId the value for ldhomework.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.class_id
     *
     * @return the value of ldhomework.class_id
     *
     * @mbg.generated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.class_id
     *
     * @param classId the value for ldhomework.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.lession_id
     *
     * @return the value of ldhomework.lession_id
     *
     * @mbg.generated
     */
    public Long getLessionId() {
        return lessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.lession_id
     *
     * @param lessionId the value for ldhomework.lession_id
     *
     * @mbg.generated
     */
    public void setLessionId(Long lessionId) {
        this.lessionId = lessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.homework_filepath
     *
     * @return the value of ldhomework.homework_filepath
     *
     * @mbg.generated
     */
    public String getHomeworkFilepath() {
        return homeworkFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.homework_filepath
     *
     * @param homeworkFilepath the value for ldhomework.homework_filepath
     *
     * @mbg.generated
     */
    public void setHomeworkFilepath(String homeworkFilepath) {
        this.homeworkFilepath = homeworkFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.homework_filename
     *
     * @return the value of ldhomework.homework_filename
     *
     * @mbg.generated
     */
    public String getHomeworkFilename() {
        return homeworkFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.homework_filename
     *
     * @param homeworkFilename the value for ldhomework.homework_filename
     *
     * @mbg.generated
     */
    public void setHomeworkFilename(String homeworkFilename) {
        this.homeworkFilename = homeworkFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.create_date
     *
     * @return the value of ldhomework.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.create_date
     *
     * @param createDate the value for ldhomework.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.correct_flag
     *
     * @return the value of ldhomework.correct_flag
     *
     * @mbg.generated
     */
    public String getCorrectFlag() {
        return correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.correct_flag
     *
     * @param correctFlag the value for ldhomework.correct_flag
     *
     * @mbg.generated
     */
    public void setCorrectFlag(String correctFlag) {
        this.correctFlag = correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.star_count
     *
     * @return the value of ldhomework.star_count
     *
     * @mbg.generated
     */
    public Integer getStarCount() {
        return starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.star_count
     *
     * @param starCount the value for ldhomework.star_count
     *
     * @mbg.generated
     */
    public void setStarCount(Integer starCount) {
        this.starCount = starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.negative_count
     *
     * @return the value of ldhomework.negative_count
     *
     * @mbg.generated
     */
    public Integer getNegativeCount() {
        return negativeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.negative_count
     *
     * @param negativeCount the value for ldhomework.negative_count
     *
     * @mbg.generated
     */
    public void setNegativeCount(Integer negativeCount) {
        this.negativeCount = negativeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldhomework.best_flag
     *
     * @return the value of ldhomework.best_flag
     *
     * @mbg.generated
     */
    public String getBestFlag() {
        return bestFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldhomework.best_flag
     *
     * @param bestFlag the value for ldhomework.best_flag
     *
     * @mbg.generated
     */
    public void setBestFlag(String bestFlag) {
        this.bestFlag = bestFlag;
    }
}